"""
ChromaDB client wrapper.

Chroma runs as its own HTTP server (start it with `chroma run --path ./chroma_data --port 8001`).
We connect via
`chromadb.HttpClient` and expose two logical collections: one for document
chunks (RAG) and one for long-term memory (semantic recall of user facts).
Embeddings themselves are generated by Ollama's nomic-embed-text model via
OllamaClient.embed(), then passed in explicitly — Chroma is used purely as
the vector index here, not as the embedding function.
"""

from typing import Any, Dict, List, Optional

import chromadb

from app.config import get_settings
from app.llm.ollama_client import get_ollama_client
from app.utils.exceptions import UpstreamServiceError
from app.utils.logger import get_logger

logger = get_logger(__name__)

_chroma_client: Optional[chromadb.HttpClient] = None


def get_chroma_client() -> chromadb.HttpClient:
    global _chroma_client
    if _chroma_client is None:
        settings = get_settings()
        _chroma_client = chromadb.HttpClient(host=settings.chroma_host, port=settings.chroma_port)
    return _chroma_client


class VectorStore:
    """Generic helper around a single Chroma collection."""

    def __init__(self, collection_name: str) -> None:
        self._collection_name = collection_name
        self._client = get_chroma_client()
        self._collection = self._client.get_or_create_collection(name=collection_name)
        self._ollama = get_ollama_client()

    async def add(self, ids: List[str], texts: List[str], metadatas: List[Dict[str, Any]]) -> None:
        try:
            embeddings = [await self._ollama.embed(text) for text in texts]
            self._collection.add(ids=ids, embeddings=embeddings, documents=texts, metadatas=metadatas)
        except Exception as exc:  # noqa: BLE001
            logger.error("chroma.add_failed", collection=self._collection_name, error=str(exc))
            raise UpstreamServiceError("Failed to index content in the vector store.") from exc

    async def query(
        self,
        query_text: str,
        n_results: int = 4,
        where: Optional[Dict[str, Any]] = None,
    ) -> List[Dict[str, Any]]:
        try:
            query_embedding = await self._ollama.embed(query_text)
            results = self._collection.query(
                query_embeddings=[query_embedding],
                n_results=n_results,
                where=where,
            )
        except Exception as exc:  # noqa: BLE001
            logger.error("chroma.query_failed", collection=self._collection_name, error=str(exc))
            raise UpstreamServiceError("Failed to query the vector store.") from exc

        documents = results.get("documents", [[]])[0]
        metadatas = results.get("metadatas", [[]])[0]
        distances = results.get("distances", [[]])[0]

        return [
            {"text": doc, "metadata": meta, "distance": dist}
            for doc, meta, dist in zip(documents, metadatas, distances)
        ]

    def delete(self, ids: List[str]) -> None:
        self._collection.delete(ids=ids)

    def delete_where(self, where: Dict[str, Any]) -> None:
        self._collection.delete(where=where)


def get_document_store() -> VectorStore:
    settings = get_settings()
    return VectorStore(settings.chroma_collection_documents)


def get_memory_store() -> VectorStore:
    settings = get_settings()
    return VectorStore(settings.chroma_collection_memory)
